spring:
  profiles:
    active: dev

#server:
#  # 端口号
#  port: 8761

eureka:
  client:
    service-url:
      # 默认注册地址
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#      defaultZone: http://localhost:${server.port}/eureka/