spring:
  profiles:
    active: dev
  application:
    # 服务名称
    name: product
server:
  # 端口号
  port: 8082

eureka:
  server:
    # 自我保护机制
#    enableSelfPreservation: false
  client:
    service-url:
      # 默认注册地址
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    # 将IP注册到Eureka Server
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${server.port}