server:
  # 端口号
  port: 8080
spring:
  application:
    # 项目名称
    name: spring-consumer

logging:
  level:
    # 显示日志级别
    com.springboot.provide.consumer.controller.IHelloControllerFeign: debug
    # 取消注册中心定时回复日志显示（info级别）
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN