-- auto Generated on 2021-02-05
-- DROP TABLE IF EXISTS `order`;
CREATE TABLE `order`(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	order_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'orderName',
	order_no VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'orderNo',
	begin_time DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'beginTime',
	end_time DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'endTime',
	is_delete TINYINT (3) NOT NULL DEFAULT 0 COMMENT 'isDelete',
	creat_by VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'creatBy',
	creat_time DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'creatTime',
	update_by VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'updateBy',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'order';
