server:
    # 端口号
    port: 8083
spring:
  application:
    # 项目名称
    name: spring-configservice
  # 配置文件获取位置(本地，使用git注释掉)
#  profiles:
#    active: native

  cloud:
    config:
      server:
        native:
#          # 配置本地路径 （使用git注释掉）
#          search-locations: file:D:/1a/config/

#        # 配置文件获取位置（git）
        git:
#          # 配置项目下的相对路径 （项目下某个文件夹）
#          search-paths: config
#          # git项目路径
          uri: https://gitee.com/IBeliveDream/spring-cloud-config-server.git
#          # git账号
#          username:
#          # git密码
#          password:
#          # 指定读取配置文件的存放路径
#          basedir:

#logging:
#  level:
#    # 显示日志级别
#    com.springboot.provide.consumer.controller.IHelloControllerFeign: debug
#    # 取消注册中心定时回复日志显示（info级别）
#    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN

